// DropMemo — a thin SwiftUI front-end over scripts/process.sh.
//
// One window: drag a recording in (or pick one), tweak a couple of controls,
// watch the pipeline's stdout stream live, and on success the out-dir is
// revealed in Finder with notes.md opened. It is deliberately NOT a
// reimplementation of the pipeline — every run shells out to scripts/process.sh
// (the single source of truth) so the app and the Voice Memos Shortcut behave
// identically.
//
// It also registers as a handler for .m4a/.wav/.mp3 (see Info.plist generated by
// scripts/build_dropmemo.sh), so "Open With ▸ DropMemo" and dropping a memo on
// the Dock icon both work.

import SwiftUI
import AppKit
import UniformTypeIdentifiers

// MARK: - Where the repo (and thus process.sh) lives

enum Repo {
    /// Resolution order: DROPMEMO_REPO env → Info.plist "DMRepoPath" (baked in
    /// at build time) → a sensible default. Keeps the .app relocatable while
    /// still finding the checkout it belongs to.
    static var path: String {
        if let env = ProcessInfo.processInfo.environment["DROPMEMO_REPO"], !env.isEmpty {
            return (env as NSString).expandingTildeInPath
        }
        if let baked = Bundle.main.object(forInfoDictionaryKey: "DMRepoPath") as? String, !baked.isEmpty {
            return (baked as NSString).expandingTildeInPath
        }
        return (("~/Documents/GitHub/my-meeting-notetaker") as NSString).expandingTildeInPath
    }

    static var processSh: String { path + "/scripts/process.sh" }
}

// MARK: - Controls

enum Backend: String, CaseIterable, Identifiable {
    case ollama = "Ollama"
    case anthropic = "Anthropic"
    var id: String { rawValue }
    /// process.sh's LLM_BACKEND value.
    var llmBackend: String { self == .ollama ? "openai" : "anthropic" }
}

enum DiarizeEngine: String, CaseIterable, Identifiable {
    case pyannote, sortformer
    var id: String { rawValue }
}

// MARK: - Model: owns the log + drives the Process

@MainActor
final class PipelineModel: ObservableObject {
    static let shared = PipelineModel()

    @Published var audioURL: URL?
    @Published var log: String = ""
    @Published var isRunning = false
    @Published var lastOutDir: String?

    // Controls strip
    @Published var backend: Backend = .ollama
    @Published var model: String = "qwen3-coder:latest"
    @Published var denoise = false
    @Published var diarize: DiarizeEngine = .pyannote

    private var task: Process?

    /// Default model name to show when the backend toggles.
    func backendChanged() {
        switch backend {
        case .ollama:    if model.isEmpty || model.contains("claude") { model = "qwen3-coder:latest" }
        case .anthropic: if model.isEmpty || !model.contains("claude") { model = "claude-opus-4-8" }
        }
    }

    func accept(_ url: URL) {
        audioURL = url
        appendLine("• selected \(url.lastPathComponent)")
    }

    func run() {
        guard let audio = audioURL, !isRunning else { return }
        guard FileManager.default.isExecutableFile(atPath: Repo.processSh) else {
            appendLine("✗ can't find process.sh at \(Repo.processSh)")
            appendLine("  Set DROPMEMO_REPO, or rebuild so DMRepoPath points at your checkout.")
            return
        }

        log = ""
        isRunning = true
        lastOutDir = nil

        // Map the controls onto process.sh's interface.
        var args = [Repo.processSh, audio.path]
        var env = ProcessInfo.processInfo.environment
        env["LLM_BACKEND"] = backend.llmBackend
        switch backend {
        case .ollama:
            env["OLLAMA_MODEL"] = model              // process.sh passes this as --model-llm
        case .anthropic:
            args += ["--model-llm", model]           // anthropic model id is a pass-through flag
        }
        if denoise { args.append("--denoise") }
        args += ["--diarize-engine", diarize.rawValue]

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/bin/bash")
        proc.arguments = args
        proc.environment = env

        let pipe = Pipe()
        proc.standardOutput = pipe
        proc.standardError = pipe
        pipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            guard !data.isEmpty, let chunk = String(data: data, encoding: .utf8) else { return }
            Task { @MainActor in PipelineModel.shared.append(chunk) }
        }

        proc.terminationHandler = { p in
            Task { @MainActor in PipelineModel.shared.finished(status: p.terminationStatus) }
        }

        self.task = proc
        appendLine("▶ processing \(audio.lastPathComponent)…\n")
        do {
            try proc.run()
        } catch {
            isRunning = false
            appendLine("✗ failed to launch: \(error.localizedDescription)")
        }
    }

    private func finished(status: Int32) {
        task?.standardOutput.flatMap { ($0 as? Pipe) }?.fileHandleForReading.readabilityHandler = nil
        task = nil
        isRunning = false
        if status == 0, let out = parseOutDir() {
            lastOutDir = out
            appendLine("\n✓ done — opening \(out)")
            reveal(out)
        } else {
            appendLine("\n✗ pipeline exited with status \(status)")
        }
    }

    /// process.sh prints `OUT_DIR=/abs/path` as its last line.
    private func parseOutDir() -> String? {
        for line in log.split(separator: "\n").reversed() where line.hasPrefix("OUT_DIR=") {
            return String(line.dropFirst("OUT_DIR=".count))
        }
        return nil
    }

    private func reveal(_ outDir: String) {
        let notes = outDir + "/notes.md"
        let fm = FileManager.default
        if fm.fileExists(atPath: notes) {
            NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: notes)])
            NSWorkspace.shared.open(URL(fileURLWithPath: notes))
        } else {
            NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: outDir)])
        }
    }

    func append(_ s: String) { log += s }
    private func appendLine(_ s: String) { log += s + "\n" }
}

// MARK: - View

struct ContentView: View {
    @ObservedObject var m = PipelineModel.shared
    @State private var dropHighlight = false

    var body: some View {
        VStack(spacing: 12) {
            dropZone
            controls
            logView
            statusBar
        }
        .padding(16)
        .frame(minWidth: 560, minHeight: 520)
    }

    private var dropZone: some View {
        ZStack {
            RoundedRectangle(cornerRadius: 12)
                .strokeBorder(style: StrokeStyle(lineWidth: 2, dash: [8]))
                .foregroundColor(dropHighlight ? .accentColor : .secondary.opacity(0.5))
                .background(
                    RoundedRectangle(cornerRadius: 12)
                        .fill(dropHighlight ? Color.accentColor.opacity(0.08) : Color.clear)
                )
            VStack(spacing: 6) {
                Image(systemName: "waveform")
                    .font(.system(size: 34))
                    .foregroundColor(.secondary)
                Text(m.audioURL?.lastPathComponent ?? "Drag a Voice Memo here")
                    .font(.headline)
                Text("or")
                    .foregroundColor(.secondary).font(.caption)
                Button("Choose file…") { pickFile() }
            }
            .padding()
        }
        .frame(height: 150)
        .onDrop(of: [UTType.fileURL], isTargeted: $dropHighlight) { providers in
            handleDrop(providers)
        }
    }

    private var controls: some View {
        HStack(spacing: 14) {
            Picker("Backend", selection: $m.backend) {
                ForEach(Backend.allCases) { Text($0.rawValue).tag($0) }
            }
            .fixedSize()
            .onChange(of: m.backend) { _ in m.backendChanged() }

            TextField("model", text: $m.model)
                .textFieldStyle(.roundedBorder)
                .frame(minWidth: 150)

            Toggle("Denoise", isOn: $m.denoise)

            Picker("Diarize", selection: $m.diarize) {
                ForEach(DiarizeEngine.allCases) { Text($0.rawValue).tag($0) }
            }
            .fixedSize()
        }
        .disabled(m.isRunning)
    }

    private var logView: some View {
        ScrollViewReader { proxy in
            ScrollView {
                Text(m.log.isEmpty ? "Pipeline output will stream here." : m.log)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(m.log.isEmpty ? .secondary : .primary)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(8)
                    .id("logTail")
            }
            .background(Color(nsColor: .textBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 8))
            .onChange(of: m.log) { _ in
                withAnimation { proxy.scrollTo("logTail", anchor: .bottom) }
            }
        }
    }

    private var statusBar: some View {
        HStack {
            if m.isRunning {
                ProgressView().controlSize(.small)
                Text("Processing…").foregroundColor(.secondary)
            } else if let out = m.lastOutDir {
                Text("Done → \(out)").foregroundColor(.secondary)
                    .lineLimit(1).truncationMode(.head)
            } else {
                Text("Ready").foregroundColor(.secondary)
            }
            Spacer()
            Button(m.isRunning ? "Running…" : "Process") { m.run() }
                .keyboardShortcut(.return, modifiers: [])
                .disabled(m.audioURL == nil || m.isRunning)
        }
    }

    // MARK: drop / pick

    private func handleDrop(_ providers: [NSItemProvider]) -> Bool {
        guard let provider = providers.first else { return false }
        _ = provider.loadObject(ofClass: URL.self) { url, _ in
            guard let url, url.isFileURL else { return }
            Task { @MainActor in PipelineModel.shared.accept(url) }
        }
        return true
    }

    private func pickFile() {
        let panel = NSOpenPanel()
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        panel.allowedContentTypes = [.audio, .mpeg4Audio, .wav, .mp3]
        if panel.runModal() == .OK, let url = panel.url {
            m.accept(url)
        }
    }
}

// MARK: - App + Open-With handling

final class AppDelegate: NSObject, NSApplicationDelegate {
    // Files opened via Finder "Open With", the Dock icon, or the Share sheet.
    func application(_ application: NSApplication, open urls: [URL]) {
        guard let url = urls.first(where: { $0.isFileURL }) else { return }
        Task { @MainActor in PipelineModel.shared.accept(url) }
    }
    func applicationShouldTerminateAfterLastWindowClosed(_ s: NSApplication) -> Bool { true }
}

@main
struct DropMemoApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var delegate

    var body: some Scene {
        Window("DropMemo", id: "main") {
            ContentView()
        }
        .windowResizability(.contentMinSize)
    }
}
