// DropMemo — a thin SwiftUI front-end over scripts/process.sh.
//
// One window: drag a recording in (or pick one), set who was in the meeting and
// the controls, watch the pipeline's stdout stream live, and on success the
// out-dir is revealed in Finder with notes.md opened. It is deliberately NOT a
// reimplementation of the pipeline — every run shells out to scripts/process.sh
// (the single source of truth) so the app and the Voice Memos Shortcut behave
// identically.
//
// It also registers as a handler for .m4a/.wav/.mp3 (see Info.plist generated by
// scripts/build_dropmemo.sh), so "Open With ▸ DropMemo" and dropping a memo on
// the Dock icon both work.

import SwiftUI
import AppKit
import Darwin
import UniformTypeIdentifiers

// MARK: - Where the repo (and thus process.sh + config.yaml) lives

enum Repo {
    /// Resolution order: DROPMEMO_REPO env → Info.plist "DMRepoPath" (baked in
    /// at build time) → a sensible default. Keeps the .app relocatable while
    /// still finding the checkout it belongs to.
    static var path: String {
        if let env = ProcessInfo.processInfo.environment["DROPMEMO_REPO"], !env.isEmpty {
            return (env as NSString).expandingTildeInPath
        }
        if let baked = Bundle.main.object(forInfoDictionaryKey: "DMRepoPath") as? String, !baked.isEmpty {
            return (baked as NSString).expandingTildeInPath
        }
        return (("~/Documents/GitHub/my-meeting-notetaker") as NSString).expandingTildeInPath
    }

    static var processSh: String { path + "/scripts/process.sh" }
    static var configPath: String { path + "/config.yaml" }
}

// MARK: - Controls

enum Backend: String, CaseIterable, Identifiable {
    case ollama = "Ollama"
    case claudeSub = "Claude (sub)"
    case anthropic = "Anthropic (API)"
    var id: String { rawValue }
    /// process.sh's LLM_BACKEND value.
    var llmBackend: String {
        switch self {
        case .ollama:    return "openai"
        case .claudeSub: return "claude-cli"   // local `claude` → subscription
        case .anthropic: return "anthropic"    // API key
        }
    }
}

enum DiarizeEngine: String, CaseIterable, Identifiable {
    case pyannote, sortformer
    var id: String { rawValue }
}

// MARK: - Model: owns the log + drives the Process

@MainActor
final class PipelineModel: ObservableObject {
    static let shared = PipelineModel()

    @Published var audioURL: URL?
    @Published var log: String = ""
    @Published var isRunning = false
    @Published var lastOutDir: String?

    // Controls strip
    @Published var backend: Backend = .ollama
    @Published var model: String = "qwen3-coder:latest"
    @Published var denoise = false
    @Published var diarize: DiarizeEngine = .pyannote
    @Published var asrModel: String = "1.7B"          // 0.6B = faster, 1.7B = accurate

    // Meeting roster — written to config.yaml on each run (the pipeline reads it
    // to name speakers). Comma- or newline-separated names.
    @Published var participants: String = ""
    @Published var context: String = ""

    private var task: Process?
    private var stopped = false

    init() { loadConfig() }

    /// Default model name to show when the backend toggles.
    func backendChanged() {
        switch backend {
        case .ollama:    if model.isEmpty || model.contains("claude") || model.contains("sonnet") || model.contains("opus") { model = "qwen3-coder:latest" }
        case .claudeSub: model = "sonnet"
        case .anthropic: if model.isEmpty || !model.contains("claude") { model = "claude-opus-4-8" }
        }
    }

    func accept(_ url: URL) {
        audioURL = url
        appendLine("• selected \(url.lastPathComponent)")
    }

    // MARK: config.yaml <-> UI

    /// Minimal reader for the `participants:` list and `context: |` block this
    /// app writes (and the example file). Not a general YAML parser.
    func loadConfig() {
        guard let text = try? String(contentsOfFile: Repo.configPath, encoding: .utf8) else { return }
        var names: [String] = []
        var ctx: [String] = []
        var inCtx = false
        for raw in text.components(separatedBy: "\n") {
            if inCtx {
                if raw.hasPrefix("  ") { ctx.append(String(raw.dropFirst(2))); continue }
                if raw.trimmingCharacters(in: .whitespaces).isEmpty { ctx.append(""); continue }
                inCtx = false
            }
            let t = raw.trimmingCharacters(in: .whitespaces)
            if t.hasPrefix("- ") {
                names.append(String(t.dropFirst(2)).trimmingCharacters(in: .whitespaces))
            } else if t.hasPrefix("context:") {
                inCtx = true
            }
        }
        if !names.isEmpty { participants = names.joined(separator: ", ") }
        let c = ctx.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
        if !c.isEmpty { context = c }
    }

    /// Write the roster fields back to config.yaml so the pipeline picks them up.
    func writeConfig() {
        let names = participants
            .split(whereSeparator: { $0 == "," || $0 == "\n" })
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        var y = "# Written by DropMemo. Edit here or in the app.\nparticipants:\n"
        for n in names { y += "  - \(n)\n" }
        let ctx = context.trimmingCharacters(in: .whitespacesAndNewlines)
        if !ctx.isEmpty {
            y += "context: |\n"
            for line in ctx.components(separatedBy: "\n") { y += "  \(line)\n" }
        }
        try? y.write(toFile: Repo.configPath, atomically: true, encoding: .utf8)
    }

    // MARK: run

    func run() {
        guard let audio = audioURL, !isRunning else { return }
        guard FileManager.default.isExecutableFile(atPath: Repo.processSh) else {
            appendLine("✗ can't find process.sh at \(Repo.processSh)")
            appendLine("  Set DROPMEMO_REPO, or rebuild so DMRepoPath points at your checkout.")
            return
        }

        writeConfig()            // roster fields → config.yaml before the run
        log = ""
        isRunning = true
        stopped = false
        lastOutDir = nil

        // Map the controls onto process.sh's interface.
        var args = [Repo.processSh, audio.path]
        var env = ProcessInfo.processInfo.environment
        env["LLM_BACKEND"] = backend.llmBackend
        switch backend {
        case .ollama:
            env["OLLAMA_MODEL"] = model              // process.sh passes this as --model-llm
        case .claudeSub, .anthropic:
            args += ["--model-llm", model]           // model id/alias is a pass-through flag
        }
        if denoise { args.append("--denoise") }
        args += ["--diarize-engine", diarize.rawValue]
        args += ["--model", asrModel]                // ASR/align size (0.6B|1.7B)

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/bin/bash")
        proc.arguments = args
        proc.environment = env

        let pipe = Pipe()
        proc.standardOutput = pipe
        proc.standardError = pipe
        pipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            guard !data.isEmpty, let chunk = String(data: data, encoding: .utf8) else { return }
            Task { @MainActor in PipelineModel.shared.append(chunk) }
        }
        proc.terminationHandler = { p in
            Task { @MainActor in PipelineModel.shared.finished(status: p.terminationStatus) }
        }

        self.task = proc
        appendLine("▶ processing \(audio.lastPathComponent)…\n")
        do {
            try proc.run()
        } catch {
            isRunning = false
            appendLine("✗ failed to launch: \(error.localizedDescription)")
        }
    }

    /// Stop a run: SIGTERM the whole process tree (bash → python → speech/ffmpeg/
    /// claude), since terminating just the bash parent would leave the heavy
    /// `speech` child running.
    func stop() {
        guard isRunning, let p = task else { return }
        stopped = true
        appendLine("\n⏹ stopping…")
        Self.killTree(pid: p.processIdentifier)
        p.terminate()
    }

    private static func killTree(pid: Int32) {
        let pgrep = Process()
        pgrep.executableURL = URL(fileURLWithPath: "/usr/bin/pgrep")
        pgrep.arguments = ["-P", "\(pid)"]
        let pipe = Pipe(); pgrep.standardOutput = pipe
        try? pgrep.run(); pgrep.waitUntilExit()
        let out = String(data: pipe.fileHandleForReading.readDataToEndOfFile(),
                         encoding: .utf8) ?? ""
        for line in out.split(separator: "\n") {
            if let child = Int32(line.trimmingCharacters(in: .whitespaces)) {
                killTree(pid: child)
            }
        }
        kill(pid, SIGTERM)
    }

    private func finished(status: Int32) {
        task?.standardOutput.flatMap { ($0 as? Pipe) }?.fileHandleForReading.readabilityHandler = nil
        task = nil
        isRunning = false
        if stopped {
            appendLine("\n⏹ stopped.")
        } else if status == 0, let out = parseOutDir() {
            lastOutDir = out
            appendLine("\n✓ done — opening \(out)")
            reveal(out)
        } else {
            appendLine("\n✗ pipeline exited with status \(status)")
        }
    }

    /// process.sh prints `OUT_DIR=/abs/path` as its last line.
    private func parseOutDir() -> String? {
        for line in log.split(separator: "\n").reversed() where line.hasPrefix("OUT_DIR=") {
            return String(line.dropFirst("OUT_DIR=".count))
        }
        return nil
    }

    private func reveal(_ outDir: String) {
        let notes = outDir + "/notes.md"
        if FileManager.default.fileExists(atPath: notes) {
            NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: notes)])
            NSWorkspace.shared.open(URL(fileURLWithPath: notes))
        } else {
            NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: outDir)])
        }
    }

    func append(_ s: String) { log += s }
    private func appendLine(_ s: String) { log += s + "\n" }
}

// MARK: - View

struct ContentView: View {
    @ObservedObject var m = PipelineModel.shared
    @State private var dropHighlight = false

    var body: some View {
        VStack(spacing: 12) {
            dropZone
            roster
            controls
            logView
            statusBar
        }
        .padding(16)
        .frame(minWidth: 580, minHeight: 640)
    }

    private var dropZone: some View {
        ZStack {
            RoundedRectangle(cornerRadius: 12)
                .strokeBorder(style: StrokeStyle(lineWidth: 2, dash: [8]))
                .foregroundColor(dropHighlight ? .accentColor : .secondary.opacity(0.5))
                .background(
                    RoundedRectangle(cornerRadius: 12)
                        .fill(dropHighlight ? Color.accentColor.opacity(0.08) : Color.clear)
                )
            VStack(spacing: 6) {
                Image(systemName: "waveform")
                    .font(.system(size: 30))
                    .foregroundColor(.secondary)
                Text(m.audioURL?.lastPathComponent ?? "Drag a Voice Memo here")
                    .font(.headline)
                Text("or").foregroundColor(.secondary).font(.caption)
                Button("Choose file…") { pickFile() }
            }
            .padding()
        }
        .frame(height: 130)
        // Accept broadly (.item) so file *promises* from Voice Memos register —
        // a plain fileURL filter silently rejects them.
        .onDrop(of: [.fileURL, .audio, .item], isTargeted: $dropHighlight) { providers in
            handleDrop(providers)
        }
    }

    private var roster: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Who's in the meeting  (saved to config.yaml)")
                .font(.caption).foregroundColor(.secondary)
            TextField("Participants, comma-separated (e.g. Tom, Olly)", text: $m.participants)
                .textFieldStyle(.roundedBorder)
            TextEditor(text: $m.context)
                .font(.system(.caption, design: .default))
                .frame(height: 56)
                .overlay(RoundedRectangle(cornerRadius: 5).stroke(.secondary.opacity(0.3)))
                .overlay(alignment: .topLeading) {
                    if m.context.isEmpty {
                        Text("Optional context: roles, who dials in, recurring topics…")
                            .font(.caption).foregroundColor(.secondary)
                            .padding(.horizontal, 5).padding(.vertical, 4).allowsHitTesting(false)
                    }
                }
        }
        .disabled(m.isRunning)
    }

    private var controls: some View {
        HStack(spacing: 14) {
            Picker("Backend", selection: $m.backend) {
                ForEach(Backend.allCases) { Text($0.rawValue).tag($0) }
            }
            .fixedSize()
            .onChange(of: m.backend) { _ in m.backendChanged() }

            TextField("model", text: $m.model)
                .textFieldStyle(.roundedBorder)
                .frame(minWidth: 140)

            Toggle("Denoise", isOn: $m.denoise)

            Picker("Diarize", selection: $m.diarize) {
                ForEach(DiarizeEngine.allCases) { Text($0.rawValue).tag($0) }
            }
            .fixedSize()

            Picker("ASR", selection: $m.asrModel) {
                Text("0.6B").tag("0.6B")        // faster
                Text("1.7B").tag("1.7B")        // accurate
            }
            .fixedSize()
            .help("Speech recognition / alignment model — 0.6B is faster, 1.7B more accurate")
        }
        .disabled(m.isRunning)
    }

    private var logView: some View {
        ScrollViewReader { proxy in
            ScrollView {
                Text(m.log.isEmpty ? "Pipeline output will stream here." : m.log)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(m.log.isEmpty ? .secondary : .primary)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(8)
                    .id("logTail")
            }
            .background(Color(nsColor: .textBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 8))
            .onChange(of: m.log) { _ in
                withAnimation { proxy.scrollTo("logTail", anchor: .bottom) }
            }
        }
    }

    private var statusBar: some View {
        HStack {
            if m.isRunning {
                ProgressView().controlSize(.small)
                Text("Processing…").foregroundColor(.secondary)
            } else if let out = m.lastOutDir {
                Text("Done → \(out)").foregroundColor(.secondary)
                    .lineLimit(1).truncationMode(.head)
            } else {
                Text("Ready").foregroundColor(.secondary)
            }
            Spacer()
            if m.isRunning {
                Button("Stop") { m.stop() }
                    .keyboardShortcut(".", modifiers: [.command])
                    .tint(.red)
            }
            Button(m.isRunning ? "Running…" : "Process") { m.run() }
                .keyboardShortcut(.return, modifiers: [])
                .disabled(m.audioURL == nil || m.isRunning)
        }
    }

    // MARK: drop / pick

    private func handleDrop(_ providers: [NSItemProvider]) -> Bool {
        guard let p = providers.first else { return false }
        // Prefer a real file representation: this materializes file *promises*
        // (how Voice Memos vends a recording) into a temp file, not just plain
        // file-URL drags. Pick an audio-conforming type id, else a file-url.
        let ids = p.registeredTypeIdentifiers
        let fileId = ids.first { UTType($0)?.conforms(to: .audio) == true }
                  ?? ids.first { $0 == UTType.fileURL.identifier }
        if let id = fileId {
            p.loadFileRepresentation(forTypeIdentifier: id) { url, _ in
                guard let url, let stable = Self.intoInbox(url) else { return }
                Task { @MainActor in PipelineModel.shared.accept(stable) }
            }
            return true
        }
        if p.canLoadObject(ofClass: URL.self) {       // Finder file drag
            _ = p.loadObject(ofClass: URL.self) { url, _ in
                guard let url, url.isFileURL else { return }
                Task { @MainActor in PipelineModel.shared.accept(url) }
            }
            return true
        }
        return false
    }

    /// The URL from loadFileRepresentation is temporary and deleted once the
    /// handler returns, so copy it somewhere stable before using it.
    private static func intoInbox(_ src: URL) -> URL? {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("DropMemo", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let dest = dir.appendingPathComponent(src.lastPathComponent)
        try? FileManager.default.removeItem(at: dest)
        do { try FileManager.default.copyItem(at: src, to: dest); return dest }
        catch { return nil }
    }

    private func pickFile() {
        let panel = NSOpenPanel()
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        panel.allowedContentTypes = [.audio, .mpeg4Audio, .wav, .mp3]
        if panel.runModal() == .OK, let url = panel.url {
            m.accept(url)
        }
    }
}

// MARK: - App + Open-With handling

final class AppDelegate: NSObject, NSApplicationDelegate {
    // Files opened via Finder "Open With", the Dock icon, or the Share sheet.
    func application(_ application: NSApplication, open urls: [URL]) {
        guard let url = urls.first(where: { $0.isFileURL }) else { return }
        Task { @MainActor in PipelineModel.shared.accept(url) }
    }
    func applicationShouldTerminateAfterLastWindowClosed(_ s: NSApplication) -> Bool { true }
}

@main
struct DropMemoApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var delegate

    var body: some Scene {
        Window("DropMemo", id: "main") {
            ContentView()
        }
        .windowResizability(.contentMinSize)
    }
}
